# This docker compose is used to setup keycloak and the database the auth microserve will use

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8020:8080
    volumes:
      - kcdata:/opt/keycloak/data
    command: start-dev

  auth-db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5420:5432
    volumes:
      - pgdata:/var/lib/postgresql
      - ./.initdb.d:/docker-entrypoint-initdb.d

volumes:
  kcdata:
  pgdata: